### ISSUE TITLE
Having trouble building this crate

### ISSUE THREAD

**Issue by gretchenfrage** [astonbitecode/j4rs#1]
Hi, I'd like to use this crate, but I'm having trouble building it. I'm running macOS High Sierra 10.13.4, I've set the JAVA_HOME path variable, but when I try to use j4rs in my crate, I get this error at compile time.

```
error: failed to run custom build command for `j4rs v0.1.2`
process didn't exit successfully: `/Users/kahlo/Desktop/rust_tower_workspace/target/debug/build/j4rs-c083517ddcb7c3ed/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-env=LD_LIBRARY_PATH=/Library/Java/Home/lib/server
cargo:rustc-link-search=native=/Library/Java/Home/lib/server

--- stderr
thread 'main' panicked at 'Initialize Environment: J4rsBuildError { description: "NotPresent" }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: std::panicking::try::do_call
             at libstd/panicking.rs:337
   7: <T as core::any::Any>::get_type_id
             at libcore/panicking.rs:92
   8: core::result::unwrap_failed
             at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:809
  10: build_script_build::main
             at ./build.rs:24
  11: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
  14: std::sys_common::at_exit_imp::push
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  16: <build_script_build::J4rsBuildError as core::fmt::Debug>::fmt
```

Any advice?

**Comment by astonbitecode** [comment]
In order for the j4rs crate to work, there is the need to have the `libjni` in the `LD_LIBRARY_PATH`.  There is a functionality in place that is adding it during the build, but it is unfortunately only for Linux...

I now removed this functionality for mac, in order not to create problems. 
Please use the latest j4rs from git and see if this helps. If so, I can release a patch on crates.io that contains this change.

Don't forget to add the `libjni` in the `LD_LIBARY_PATH` though...

**Comment by astonbitecode** [comment]
Ok I released the v0.1.3 on crates.io that should correct your issue.

Please use this and tell me if it helped. Don't forget to add the `libjni` in your `LD_LIBARY_PATH`.

**Comment by gretchenfrage** [comment]
Hey astonbitecode, sorry for not responding (got really busy with a few things). I ended up going with raw JNI for now for this particular project, but in all likelihood, I will use your utility in the future. Thank you!

**Comment by gretchenfrage** [comment]
But hey, let's get this to compile :^). Look here
https://github.com/astonbitecode/j4rs/blob/master/rust/src/utils.rs
There is no implementation of classpath_sep() for mac.

**Comment by astonbitecode** [comment]
Hi @gretchenfrage , thank you very much for the help. 

I tried to use [cross](https://github.com/rust-embedded/cross) to  ensure the crate builds correctly under more architectures, but the fact that the Java environment is needed for building j4rs brings some difficulties... I will need to go deeper to achieve a correct configuration.

Until then, I made a small change to fix the latest issue You got into (regarding the classpath_sep). 

If you find time, can you check if this fixes the compilation for Mac?

**Comment by astonbitecode** [comment]
So I included a configuration in Travis in order to build the crate in both osx and linux. 

Building now [succeeds](https://travis-ci.org/astonbitecode/j4rs/builds/422965292). However, I see one test regarding callbacks from Java to Rust [fails for osx](https://travis-ci.org/astonbitecode/j4rs/jobs/422962608). 

I will open a new issue for this.

@gretchenfrage thanks for the report and for the help.
