### ISSUE TITLE
is there way to hook java method  at runtime

### ISSUE THREAD

**Issue by andrewpedia** [astonbitecode/j4rs#108]

**Comment by astonbitecode** [comment]
Hi.

You have [opened this issue before](https://github.com/astonbitecode/j4rs/issues/99) and I asked for more details...

I would kindly ask again: Can you please describe what you try to achieve? There is no way to answer some question if there are no details.

**Comment by andrewpedia** [comment]
for example, there is a jar file,which works for android os , I need to hook the unsupported method call in java code ,because that depends on native system api ,I just want to bypass it,

**Comment by astonbitecode** [comment]
You cannot change the behavior of a method. If the method calls a native function, it will call it regardless.
