### ISSUE TITLE
Is there a way to use one single JVM on multiple invocations

### ISSUE THREAD

**Issue by davidjwriter** [astonbitecode/j4rs#109]
I have a use case where I want my Rust program to act as a middle man from JavaScript to Java code. But don’t want to have to rebuild a new JVM on every invocation. Is there a way to create a constantly running JVM and then re-attach to that JVM every time I call into Rust?

**Comment by astonbitecode** [comment]
`j4rs` creates _one_ [`JavaVM`](https://docs.rs/jni-sys/latest/jni_sys/type.JavaVM.html) per process. This is done implicitly the first time someone uses `JvmBuilder::buiid()`. `j4rs` checks whether the `JavaVM` is created and if not, it creates one. 

The `Jvm` returned by `JvmBuilder::build` contains a [`JNINativeInterface`](https://docs.rs/jni-sys/latest/jni_sys/union.JNINativeInterface_.html), which is attached to the running rust thread. Therefore, when you want to have a new `Jvm`, `JavaVM` is not created again; what happens is actually just attaching to the new thread. If  you create one more `Jvm` in _the same_ thread, no attaching is done and this is considered a no-op (you may check the [JNI specification](https://docs.oracle.com/en/java/javase/17/docs/specs/jni/design.html) for more details).

That being said, you can be explicit and if you know that you have created a `Jvm` earlier in the process, you can use the `Jvm::attach_thread` to get a `Jvm`. Generally, you can save `Jvm`s in thread local, but you cannot use the same `Jvm` in multiple threads: `Jvm` is not `Send`. 

Note: `Jvm` is not `Send`, but `Instance`s returned by invocations are `Send` and can be safely used by different threads.

**Comment by davidjwriter** [comment]
Ok, that sounds like great news! Thanks for the explanation!

I'm trying to test this out to see if it works, but running into issues building with wasm-pack. Have you successfully built J4RS projects to wasm before?

**Comment by astonbitecode** [comment]
I have not tried using in wasm, but users opened [this](https://github.com/astonbitecode/j4rs/issues/53) and [this](https://github.com/astonbitecode/j4rs/issues/67) issue, please read the discussions.

 In the latter one, the dev claims they achieved what they wanted. The former, had issues, but since then, we have in `j4rs` the `no-runtime-libloading` feature, which _could_ resolve the issue this dev had.

**Comment by davidjwriter** [comment]
Those are my exact errors I'm running into with the libc stuff. I'll look through them, thanks for the quick responses!
