### ISSUE TITLE
Are invocations to Java done through reflection?

### ISSUE THREAD

**Issue by pickleburger** [astonbitecode/j4rs#112]
It seems invocations to Java are delegated to a Java proxy class which uses reflection to figure out the right method. Is it true? Can I make direct invocations without reflection?

**Comment by astonbitecode** [comment]
Yes it us true. The invocations are done only via reflection and there is no way to directly invoke. 

If it is useful, I could implement a function to get the `jobject` and manipulate it as you want outside `j4rs`.

**Comment by pickleburger** [comment]
Yeah, that would be very helpful.

**Comment by pickleburger** [comment]
I think there is already a `java_object` function to retrieve the underlying `jobject` of an `Instance`. Can you also provide a way retrieve the `jni_env` inside `Jvm`?

**Comment by astonbitecode** [comment]
This is the `jobject` of the "proxy" class it is not the actual object you need to manipulate. I will impl what is needed and comment.

**Comment by astonbitecode** [comment]
`Jvm::instance_into_raw_object`: Consumes an `Instance` and returns its jobject. The returned jobject is a JNI local reference.

`Jvm::into_raw`: Consumes the `Jvm` and returns its `JNIEnv`

**Comment by pickleburger** [comment]
Thanks! It works for me. Wondering if you can release this feature?

**Comment by astonbitecode** [comment]
Sure, I will release in a few days.

Thanks for the report
