### ISSUE TITLE
Exception in thread "main" org.astonbitecode.j4rs.errors.InstantiationException: Cannot create instance of com.xxx.aa.bb$1903

### ISSUE THREAD

**Issue by andrewpedia** [astonbitecode/j4rs#113]
how to pass name for "com.xxx.aa.bb$1903"
the code is at below:

    let _static_invocation_result = jvm.invoke_static(
    "com.xxx.aa.bb$1903",     // The Java class to invoke
    "fff",    // The static method of the Java class to invoke
    &[InvocationArg::from(java_map_instance),InvocationArg::from(string_instance)], // The `InvocationArg`s to use for the invocation - empty for this example
  )?;

thanks a lot

**Comment by astonbitecode** [comment]
JNI naming limitations need to be taken into consideration (please have a look [here](https://docs.oracle.com/en/java/javase/17/docs/specs/jni/design.html#resolving-native-method-names) for more details).

For your example, you should use the UTF-16 escaping of the `$` character, which is `_00024`:

```rust
#[call_from_java("icom.xxx.aa.bb_000241903")]
```

**Comment by astonbitecode** [comment]
For calling Rust -> Java, this works for invoking an inner class:

```rust
let _ = jvm
            .invoke_static(
                "my.Test$InnerMyTest",
                "doSomething",
                InvocationArg::empty(),
            );
```

**Comment by andrewpedia** [comment]
so what is wrong with my code

**Comment by astonbitecode** [comment]
It depends on the Java side, how the method looks like.  Can you share some code on the Java side?

**Comment by astonbitecode** [comment]
Ok, as asked many times, please provide more details on what you want instead of arbitrarily opening issues.

In order to finish with this and the [other](https://github.com/astonbitecode/j4rs/issues/114) (possibly duplicate) issue you have opened, here is the thing:

If you have in Java the following:

```java
public class MyTest {
    public static class MyInnerStaticTest {
        public void myInnerMethod() {
            System.out.println("I am a method of a static inner class");
        }

        public static void myInnerStaticMethod() {
            System.out.println("I am a static method of a static inner class");
        }
    }
}
```

You can call the inner methods of the class from Rust like:
```rust
        let _ = jvm
            .invoke_static(
                "x.y.z.MyTest$MyInnerStaticTest",
                "myInnerStaticMethod",
                InvocationArg::empty(),
            )?;

        let instance = jvm
            .create_instance(
                "x.y.z.MyTest$MyInnerStaticTest",
                InvocationArg::empty(),
            )?;
        let _ = jvm.invoke(&instance, "myInnerMethod", InvocationArg::empty())?;
```

If you have in Java the following:

```java
public class MyTest {
    public class MyInnerTest {
        public void myInnerMethod() {
            System.out.println("I am an method of a non-static inner class");
        }
    }
}
```

You can call the inner methods of the class from Rust like:

```rust
        let outer = jvm
            .create_instance(
                "x.y.z.MyTest",
                InvocationArg::empty(),
            )?;
        let inner = jvm
            .create_instance(
                "x.y.z.MyTest$MyInnerTest",
                &[InvocationArg::try_from(outer)?],
            )?;
        let _ = jvm.invoke(&inner, "myInnerMethod", InvocationArg::empty())?;
```

**Comment by andrewpedia** [comment]
thanks
