### ISSUE TITLE
 java.lang.IllegalAccessException: class org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl cannot access a member of class com.xxx.aa.bb$290 with modifiers "public static"

### ISSUE THREAD

**Issue by andrewpedia** [astonbitecode/j4rs#114]
let string_instance = jvm.create_instance(
                "java.lang.String",
                &[InvocationArg::try_from(" a string ")?],
              )?;
 
   let _static_invocation_result = jvm.invoke_static(
    "com.xxx.aa.bb$290",     // The Java class to invoke
    "ffff",    // The static method of the Java class to invoke
    &[InvocationArg::from(string_instance)], // The `InvocationArg`s to use for the invocation - empty for this example
  )?;

**Comment by astonbitecode** [comment]
Maybe the method is not public...

**Comment by andrewpedia** [comment]
it is sure public

**Comment by astonbitecode** [comment]
Maybe not static? Can you share some code?
