### ISSUE TITLE
instanceof

### ISSUE THREAD

**Issue by lxl66566** [astonbitecode/j4rs#126]
Hello, I wonder if an `Instance` is 'instanceof' a Class?

I tried to compare `Instance::class_name()`, but I only got `known_in_java_world`.

**Comment by astonbitecode** [comment]
`Instance`s are kind of proxies for Java classes. The `Instance::class_name()` is considered internal API and probably should be hidden by the users. 

Having said that, you could get the class name of an `Instance` simply by calling its java respective methods:

```rust
let jvm = JvmBuilder::new().build()?;
let test_instance = jvm.create_instance("org.astonbitecode.j4rs.tests.MyTest", InvocationArg::empty())?;
let classname_string_instance = jvm
    .chain(&test_instance)?
    .invoke(
        "getClass",
         InvocationArg::empty(),
    )?
    .invoke("getName", InvocationArg::empty())?
    .collect();
let classname: String = jvm.to_rust(classname_string_instance)?;
println!("The classname is: {classname}");
```

**Comment by lxl66566** [comment]
Thank you!
