### ISSUE TITLE
`j4rs` tries to open a file it has nothing to do with, `GeneralError("Error { kind: PermissionDenied, message: \"Permission denied (os error 13)\" }`

### ISSUE THREAD

**Issue by Notwatch** [astonbitecode/j4rs#128]
For some reason, it tries to open a file that is not related to anything (?)
so it panics when trying to open a file it doesn't have permission for.

```
statx(AT_FDCWD, "/srv/app/volumes/cache/dump.rdb", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0600, stx_size=89, ...}) = 0
getdents64(5, 0x6502a330fc20 /* 0 entries */, 32768) = 0
close(5)                                = 0
statx(AT_FDCWD, "/srv/app/volumes/database", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=4096, ...}) = 0
statx(AT_FDCWD, "/srv/app/volumes/database", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=4096, ...}) = 0
openat(AT_FDCWD, "/srv/app/volumes/database", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 5
fstat(5, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
getdents64(5, 0x6502a330fc20 /* 3 entries */, 32768) = 80
statx(AT_FDCWD, "/srv/app/volumes/database/pgdata", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0700, stx_size=4096, ...}) = 0
statx(AT_FDCWD, "/srv/app/volumes/database/pgdata", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0700, stx_size=4096, ...}) = 0
openat(AT_FDCWD, "/srv/app/volumes/database/pgdata", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 EACCES (Permission denied)
```

for context, the executable is located at `/srv/app/servers/auth/auth`.

This error only happens after I copied the executable from its original path `/srv/app/sources/auth/target/release/auth` (and yes, it runs normally if I execute it from the original path without copying/moving it to the new path).

I assume that it has something to do with this code (?), but I might be wrong.
https://github.com/astonbitecode/j4rs/blob/93608e40f6ff962bb91f2d6bb202a8dd139a280f/rust/src/utils.rs#L85-L105

**Comment by astonbitecode** [comment]
In order to place the executable in other places, you should follow the assumptions mentioned [here](https://github.com/astonbitecode/j4rs?tab=readme-ov-file#portability-assumptions-after-rust-build-shipping-a-j4rs-application).

Please, give it a try and see if it works.

**Comment by Notwatch** [comment]
Thanks, that works!
