### ISSUE TITLE
HEELP

### ISSUE THREAD

**Issue by suprohub** [astonbitecode/j4rs#131]
10-31 19:45:41.736 10253 10253 F DEBUG   : Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.ClassNotFoundException: Didn't find class "org.astonbitecode.j4rs.api.dtos.InvocationArg"

**Comment by suprohub** [comment]
i get this error on android

**Comment by suprohub** [comment]
i use jni onload and attach thread but if i try create instance i get this error

**Comment by astonbitecode** [comment]
Something seems to be wrong with your classpath. It seems the `j4rs` classes are not found and cannot be loaded.

How do you setup your Android app? Is it a Java application that calls Rust native code?
If so, have you checked the example project [here](https://github.com/astonbitecode/j4rs-android-test)?

There should not be any classloading issues if:

1. You [specify](https://github.com/astonbitecode/j4rs-android-test/blob/58fb959dc83e8fa3d1dbfb3f073e2ee4c5c1c493/app/build.gradle#L37) the `j4rs` dependency in the Gradle (or Maven).
2. You have a `JNI_OnLoad` where you [set the `JavaVM`](https://github.com/astonbitecode/j4rs-android-test/blob/58fb959dc83e8fa3d1dbfb3f073e2ee4c5c1c493/j4rstestnative/src/lib.rs#L9).
3. You [load](https://github.com/astonbitecode/j4rs-android-test/blob/58fb959dc83e8fa3d1dbfb3f073e2ee4c5c1c493/app/src/main/java/com/example/j4rstest/RustFunctionCalls.java#L15) the native library in Java.
4. You [attach](https://github.com/astonbitecode/j4rs-android-test/blob/58fb959dc83e8fa3d1dbfb3f073e2ee4c5c1c493/j4rstestnative/src/lib.rs#L25) the thread and [create](https://github.com/astonbitecode/j4rs-android-test/blob/58fb959dc83e8fa3d1dbfb3f073e2ee4c5c1c493/j4rstestnative/src/lib.rs#L29) the `InvocationArg`.

**Comment by suprohub** [comment]
> Something seems to be wrong with your classpath. It seems the `j4rs` classes are not found and cannot be loaded.
> 
> How do you setup your Android app? Is it a Java application that calls Rust native code? If so, have you checked the example project [here](https://github.com/astonbitecode/j4rs-android-test)?
> 
> There should not be any classloading issues if:
> 
>     1. You [specify](https://github.com/astonbitecode/j4rs-android-test/blob/58fb959dc83e8fa3d1dbfb3f073e2ee4c5c1c493/app/build.gradle#L37) the `j4rs` dependency in the Gradle (or Maven).
> 
>     2. You have a `JNI_OnLoad` where you [set the `JavaVM`](https://github.com/astonbitecode/j4rs-android-test/blob/58fb959dc83e8fa3d1dbfb3f073e2ee4c5c1c493/j4rstestnative/src/lib.rs#L9).
> 
>     3. You [load](https://github.com/astonbitecode/j4rs-android-test/blob/58fb959dc83e8fa3d1dbfb3f073e2ee4c5c1c493/app/src/main/java/com/example/j4rstest/RustFunctionCalls.java#L15) the native library in Java.
> 
>     4. You [attach](https://github.com/astonbitecode/j4rs-android-test/blob/58fb959dc83e8fa3d1dbfb3f073e2ee4c5c1c493/j4rstestnative/src/lib.rs#L25) the thread and [create](https://github.com/astonbitecode/j4rs-android-test/blob/58fb959dc83e8fa3d1dbfb3f073e2ee4c5c1c493/j4rstestnative/src/lib.rs#L29) the `InvocationArg`.

not works

**Comment by suprohub** [comment]
i attach tread, add this to dependencies, load libary and only crashes

**Comment by suprohub** [comment]
```
                    if textedit.gained_focus() {
                        let jvm = Jvm::attach_thread().unwrap();
                        let instance = jvm.create_instance(
                            "pumpkin_egui_android.MainActivity",
                            InvocationArg::empty()
                        ).unwrap();
                        jvm.invoke(
                            &instance,
                            "openKeyboard",
                            InvocationArg::empty()
                        ).unwrap();
                    }
```

**Comment by suprohub** [comment]
```|
  public void openKeyboard() {
    InputMethodManager imm =
            (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
    if (imm != null) {
        imm.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0);
    }
  }```

**Comment by suprohub** [comment]
```
plugins {
    id 'com.android.application'
}

android {
    namespace "local.pumpkin_egui_android"
    compileSdk 33

    defaultConfig {
        applicationId "local.pumpkin_egui_android"
        minSdk 28
        targetSdk 33
        versionCode 1
        versionName "1"
    }

    buildTypes {
        debug
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.google.android.material:material:1.5.0'
    implementation "androidx.games:games-activity:2.0.2"
    implementation 'io.github.astonbitecode:j4rs:0.20.0'
}

```

**Comment by suprohub** [comment]
@Snowii

**Comment by astonbitecode** [comment]
I have just tested the [example](https://github.com/astonbitecode/j4rs-android-test) using the latest `j4rs` without issues. 

When do you call the `System.loadLibrary`? 
At the time it is called, the `JNI_OnLoad` is called and you should have there:

```rust
j4rs::set_java_vm
```

**Comment by suprohub** [comment]
> I have just tested the [example](https://github.com/astonbitecode/j4rs-android-test) using the latest `j4rs` without issues. 
> 
> When do you call the `System.loadLibrary`? 
> At the time it is called, the `JNI_OnLoad` is called and you should have there:
> 
> ```rust
> j4rs::set_java_vm
> ```

I call it from static in class, its needed for egui, set java vm i call too

**Comment by astonbitecode** [comment]
Do you maybe have some code to share?

**Comment by suprohub** [comment]
https://github.com/suprohub/Pumpkin/tree/android

**Comment by suprohub** [comment]
Go to pumpkin egui

**Comment by astonbitecode** [comment]
I am having difficulty to understand the setup of the project.

I see that you define a [MainActivity](https://github.com/suprohub/Pumpkin/blob/f40cf07bf15f8b0b4d829565645740ecdc5cbb78/pumpkin-egui/pumpkin-egui-android/java/app/src/main/AndroidManifest.xml#L10) in your `AndroidManifest`, but using also [game-activity](https://github.com/suprohub/Pumpkin/blob/f40cf07bf15f8b0b4d829565645740ecdc5cbb78/pumpkin-egui/pumpkin-egui-android/Cargo.toml#L17).

How do you build your project, create the `apk` and run it?

**Comment by suprohub** [comment]
Cargo ndk then gradle build
How verify what jni on load is called?

**Comment by suprohub** [comment]
And i want help: what the bestethod: construct main activity for call method or inline method?

**Comment by suprohub** [comment]
Like call all method code in rust

**Comment by suprohub** [comment]
See makefile

**Comment by astonbitecode** [comment]
> How verify what jni on load is called?

Using some logging I guess

> construct main activity for call method or inline method?

As  you see in the example project mentioned above, currently, the supported way is to implement the main activity in Java, use JNI_OnLoad and call the native method from Java to Rust. 

I am also investigating "rust-only" ways, using `native-activity`, but there are currently classloading [issues](https://github.com/rust-mobile/android-activity/issues/169) we need to overcome...

**Comment by suprohub** [comment]
Yeah its setted

**Comment by suprohub** [comment]
![Screenshot_20241102-113524_Pumpkin server.png](https://github.com/user-attachments/assets/e0a790e1-fbd6-4830-8e47-9219ea7c04b1)

**Comment by suprohub** [comment]
I dont know what its wrong

**Comment by suprohub** [comment]
![2024-11-02-11-54-39-705.jpg](https://github.com/user-attachments/assets/4a0181df-2789-4ca5-b5fe-adbe9d02989e)
![2024-11-02-11-54-32-465.jpg](https://github.com/user-attachments/assets/af713a82-b4bb-48f4-b8f7-dd66cedf0561)

**Comment by suprohub** [comment]
But gradle build works

**Comment by suprohub** [comment]
Any updates?

**Comment by suprohub** [comment]
Helo?

**Comment by astonbitecode** [comment]
How does the app load the activity? Is the native activity used, or the activity you implemented?

You can open the apk and inspect:

1. Which Activity is it used? (`android:name` element)
2. Do `j4rs` classes exist inside .dex files? If the classes are not there, check if code shrinking is enabled. You should [configure which code to keep](https://developer.android.com/studio/build/shrink-code#keep-code) in that case. Configuring proper keep rules is important because the code shrinker might otherwise remove classes, methods, or fields that are only used from JNI. ([source](https://developer.android.com/training/articles/perf-jni#faq:-why-didnt-findclass-find-my-class))

**Comment by astonbitecode** [comment]
For more details, please see this [example project](https://github.com/astonbitecode/j4rs-android-activity).
