### ISSUE TITLE
Is the groud parameter miss?

### ISSUE THREAD

**Issue by zhengxiwan** [astonbitecode/j4rs#15]
https://github.com/astonbitecode/j4rs/blob/d90c23c52782df731824907d8ab53511bad8bdbd/java/src/main/java/org/astonbitecode/j4rs/api/deploy/SimpleMavenDeployer.java#L53

jar will be downloaded repeatedly

**Comment by astonbitecode** [comment]
The names of jar artifacts do not include the group id. The group id is part of the path where the jar is located in.

For example, the [see the jackson-core](https://search.maven.org/artifact/com.fasterxml.jackson.core/jackson-core/2.10.3/bundle) for JSON parsing. The maven dependency is declared like:

```xml
<dependency>
  <groupId>com.fasterxml.jackson.core</groupId>
  <artifactId>jackson-core</artifactId>
  <version>2.10.3</version>
  <type>bundle</type>
</dependency>
```
and the its jar artifact is located [here](https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-core/2.10.3/), with name `jackson-core-2.10.3.jar`.

**Comment by zhengxiwan** [comment]
https://github.com/astonbitecode/j4rs/blob/d90c23c52782df731824907d8ab53511bad8bdbd/java/src/main/java/org/astonbitecode/j4rs/api/deploy/SimpleMavenDeployer.java#L68

```
    boolean artifactExists(String groupId, String artifactId, String version, String qualifier) {
        String jarName = generateArtifactName(artifactId, version, qualifier);
        String pathString = generatePathTagret(deployTarget, groupId, artifactId, version, jarName);
        return new File(pathString).exists();
    }
```

Sorry, I didn't make it clear.  
I find that `artifactExists` the return value is always false . The reason is that
` (deployTarget + File.separator + jarName)  != pathString ` , causes the jar to be downloaded repeatedly , is the bug ?

**Comment by astonbitecode** [comment]
Yes, you are right, this is a bug!

Thanks for reporting.
