### ISSUE TITLE
invalid message in JsonCodecException

### ISSUE THREAD

**Issue by xeodon** [astonbitecode/j4rs#16]
JsonValueImpl(Object obj): using nullable json intstead obj from parameter

**Comment by astonbitecode** [comment]
I am not sure if this was the issue that you encountered, but I pushed an improvement for better handling null values. 

If this is not enough, please give a description of what you are trying to achieve.

**Comment by xeodon** [comment]
```
    JsonValueImpl(Object obj) {
        this.obj = obj;
        try {
            this.json = codec.encode(obj);
        } catch (JsonProcessingException error) {
            // this.json is always null on marshalling error, exception message without obj.toString()
            throw new JsonCodecException("While creating JsonValueCallbackImpl: Could not encode " + json, error); 
        }
        this.className = obj.getClass().getName();
    }

```

**Comment by astonbitecode** [comment]
Oh ok. Anyway, this was a good opportunity for null handling improvement as well. 

Note that `obj` now is never null. 

Thanks for reporting.
