### ISSUE TITLE
How to Create Vec<ClasspathEntry<'a>>for use with  jvm::new().classpath_entries()?

### ISSUE THREAD

**Issue by jtmorrisbytes** [astonbitecode/j4rs#18]
Hello, I am new to rust and am having trouble collecting classpaths from Vec<PathBuf> -> Vec<String > -> Vec<ClasspathEntry>

I am building up my classpath entries using Vec<String>, mapping over an iterator passing a reference to ClasspathEntry::new() with the argument of the closure, but am running into ownership and lifetime issues. Are there any suggestions on how to use/collect Vecs to satisfy the lifetime issues?

**Comment by astonbitecode** [comment]
I am not sure about the exact use case, but for example consider the following:

```rust
// Start with an initial Vec
// The following is a Vec<&str>
let entries_str_vec = vec!["myjar1", "myjar2"];

// Entries manipulation
let classpath_entries = entries_str_vec.iter()
   // Do something with the elements of the initial Vec
   // Here, s is a &&str
   .map(|s| s.trim())
   // Create a ClasspathEntry for each trimmed element
   /// Here, s_trimmed is a &str, so it is used as argument in the ClasspathEntry as is.
   .map(|s_trimmed| ClasspathEntry::new(s_trimmed))
   // collect and get a Vec<ClasspathEntry>
   .collect();

// Use the classpath_entries Vec
let jvm = JvmBuilder::new()
   .classpath_entries(classpath_entries)
   .build()
   .unwrap();
```

**Comment by jtmorrisbytes** [comment]
Thanks for the example.
