### ISSUE TITLE
Passing null

### ISSUE THREAD

**Issue by fenhl** [astonbitecode/j4rs#21]
How do I create an [`InvocationArg`](https://docs.rs/j4rs/0.11.2/j4rs/enum.InvocationArg.html) that represents Java's `null`?

**Comment by astonbitecode** [comment]
This is not yet supported, but I will have something ready shortly.

**Comment by astonbitecode** [comment]
So, in order to create a null InvocationArg, you should do something like:

```rust
let null_string = InvocationArg::from(Null::String);                // A null String
let null_integer = InvocationArg::from(Null::Integer);              // A null Integer
let null_obj = InvocationArg::from(Null::Of("java.util.List"));    // A null object of any other class. E.g. List
```

Please tell me if this suits your needs. If so, I can create a patch release in order to be able to use it from an _"official"_ version in the crates.io.

**Comment by fenhl** [comment]
I actually don't need null in the current version of my project anymore, but this seems like a reasonable API and would have helped in the situation I was in.

**Comment by astonbitecode** [comment]
Ok. It was a good opportunity to implement this anyway.

Thank you.
