### ISSUE TITLE
Including underscores in the method name Java binds the Rust lib to always causes UnsatisfiedLinkError

### ISSUE THREAD

**Issue by uglyluigi** [astonbitecode/j4rs#22]
Hi there,

Currently I'm using this project to use Rust libraries in a Kotlin project I'm working on. I discovered a weird limitation I didn't notice in the docs, which is that if you include an underscore in the name of the method your Rust function corresponds to in Java, Java always emits an UnsatisfiedLinkError at runtime. Like so:

Main.kt
```
package bot

import bindings.RustDefs

open class Main {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            RustDefs.example_method()
        }
    }
}
```

RustDefs.java
```
package bindings;

public class RustDefs {
    public static native void example_method();

    static {
       System.loadLibrary("Rust");
    }
}
```

lib.rs
```
use j4rs::prelude::*;
use j4rs_derive::*;

#[call_from_java("bindings.RustDefs.example_method")]
fn example_method() {
    println!("Hello from the Rust world!");
}
```

With everything in place and the library linking correctly, the JVM emits this error when attempting to call RustDefs.example_method:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void bindings.RustDefs.example_method()'
	at bindings.RustDefs.example_method(Native Method)
	at bot.Main$Companion.main(Main.kt:9)
	at bot.Main.main(Main.kt)
```

Whenever lib.rs is amended to instead bind to a method named `exampleMethod` and the method is changed to match that name in RustDefs.java, everything works as expected.

My environment is Windows 10, using rustc 1.45.0 and targeting Java 7 for my Kotlin project.

**Comment by astonbitecode** [comment]
Hi, jni is used behind the scenes to achieve the calls from Java to Rust. This means that some conventions that hold for jni, should hold for j4rs too.

For your case specifically, you should [escape the underscore of the method](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/design.html#wp133) with a `_1` in the `call_from_java` statement.

So, you should have something like:

```rust
#[call_from_java("bindings.RustDefs.example_1method")]
```
I will update the documentation to mention about the conventions.

Thanks

**Comment by uglyluigi** [comment]
I suspected this wasn't a bug but instead an undocumented quirk. In glad you decided to document it! Thanks for your help.
