### ISSUE TITLE
`No Java runtime present, requesting install.` on OSX

### ISSUE THREAD

**Issue by schmidmt** [astonbitecode/j4rs#27]
Using j4rs version 0.13, on OSX 10.15.6, j4rs show the output `No Java runtime present, requesting install.` when using OracleJDK 14.02.

`JAVA_HOME` is set to point to the location of the JDK.

Here's the output from a DEBUG level log:
```
running 1 test
20:33:38 [INFO] Setting classpath to -Djava.class.path=/Users/schmidmt/code/target/debug/jassets/j4rs-0.13.0-jar-with-dependencies.jar:../../simulator/Sim.jar
20:33:38 [INFO] Setting library path to -Djava.library.path=/Users/schmidmt/code/target/debug/deps:/usr/lib:/lib
20:33:38 [INFO] Passing to the Java world the name of the library to load: j4rs
20:33:38 [DEBUG] j4rs::logger: Creating a Jvm
20:33:38 [INFO] No JVMs exist. Creating a new one...
20:33:39 [DEBUG] j4rs::logger: Called set_jni_get_method_id
20:33:39 [DEBUG] j4rs::logger: Called set_jni_get_static_method_id
20:33:39 [DEBUG] j4rs::logger: Called set_jni_new_object
20:33:39 [DEBUG] j4rs::logger: Called set_jni_new_string_utf
20:33:39 [DEBUG] j4rs::logger: Called set_jni_get_string_utf_chars
20:33:39 [DEBUG] j4rs::logger: Called set_jni_release_string_utf_chars
20:33:39 [DEBUG] j4rs::logger: Called set_jni_call_object_method
20:33:39 [DEBUG] j4rs::logger: Called set_jni_call_float_method
20:33:39 [DEBUG] j4rs::logger: Called set_jni_call_double_method
20:33:39 [DEBUG] j4rs::logger: Called set_jni_call_void_method
20:33:39 [DEBUG] j4rs::logger: Called set_jni_call_static_object_method
20:33:39 [DEBUG] j4rs::logger: Called set_jni_new_object_array
20:33:39 [DEBUG] j4rs::logger: Called set_jni_set_object_array_element
20:33:39 [DEBUG] j4rs::logger: Called set_jni_exception_check
20:33:39 [DEBUG] j4rs::logger: Called set_jni_exception_describe
20:33:39 [DEBUG] j4rs::logger: Called set_jni_exception_clear
20:33:39 [DEBUG] j4rs::logger: Called set_jni_delete_local_ref
20:33:39 [DEBUG] j4rs::logger: Called set_jni_delete_global_ref
20:33:39 [DEBUG] j4rs::logger: Called set_jni_new_global_ref
20:33:39 [DEBUG] j4rs::logger: Called set_jni_throw_new
20:33:39 [DEBUG] j4rs::logger: Called set_is_same_object
20:33:39 [DEBUG] j4rs::logger: Called set_thread_local_env
20:33:39 [DEBUG] j4rs::logger: Initializing NativeCallbackSupport with libname j4rs
20:33:39 [DEBUG] j4rs::logger: Invoking static method initialize of class org.astonbitecode.j4rs.api.invocation.NativeCallbackToRustChannelSupport using 1 arguments
20:33:39 [DEBUG] j4rs::logger: Called set_factory_class
20:33:39 [DEBUG] j4rs::logger: Called set_factory_create_for_static_method
20:33:39 [DEBUG] j4rs::logger: Called set_invocation_arg_class
20:33:39 [DEBUG] j4rs::logger: Creating jobject from Rust basic for class java.lang.String
20:33:39 [DEBUG] j4rs::logger: Calling the InvocationArg constructor with 'java.lang.String'
20:33:39 [DEBUG] j4rs::logger: Called set_inv_arg_basic_rust_constructor_method
20:33:39 [DEBUG] j4rs::logger: Called set_java_instance_class
20:33:39 [DEBUG] j4rs::logger: Called set_invoke_static_method
20:33:39 [DEBUG] j4rs::logger: Dropping an instance of known_in_java_world
20:33:39 [DEBUG] j4rs::logger: Dropping an instance of java.lang.String
20:33:39 [DEBUG] j4rs::logger: NativeCallbackSupport initialized
20:33:39 [DEBUG] j4rs::logger: Instantiating class ab.demo.KDLSimulation using 0 arguments
20:33:39 [DEBUG] j4rs::logger: Called set_factory_instantiate_method
20:33:39 [DEBUG] j4rs::logger: Invoking method solve of class ab.demo.KDLSimulation using 1 arguments
20:33:39 [DEBUG] j4rs::logger: Creating jobject from Rust basic for class java.lang.String
20:33:39 [DEBUG] j4rs::logger: Calling the InvocationArg constructor with 'java.lang.String'
20:33:39 [DEBUG] j4rs::logger: Called set_invoke_method
./logs/sim49243.log%g.txt 500000000 40 false
No Java runtime present, requesting install.
error: test failed, to rerun pass '--bin scibird-agent'
```

This code runs correctly on debian 10.5.

Any ideas?

**Comment by astonbitecode** [comment]
I changed the Travis CI configuration to use the JDK14.2 from Oracle and the tests [succeed](https://travis-ci.org/github/astonbitecode/j4rs/jobs/738220168).

IMHO, this looks like an issue in your environment. Searching around, I found this (rather old) [thread](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=7131356) in which they discuss that such problems appear in *"OS X machines where the default system Java is not installed"* :

> The symptoms:
>
> On those OS X machines where the default system Java is not installed, any attempt to instantiate JVM from a local JDK (for example via JNI as shown in the bug) presents "No Java installed. Do you want to install Java?" dialog and refuses to run. Clearly, a valid local JDK should be able to run in this case.

I don't have OSX available locally and I try to locate any errors or misconfigurations from Travis CI. 

What you could try, in order to see which JDK is used by `j4rs`, is the following:

1. Install java_locator from crates.io:
 `cargo install java-locator --features build-binary` 
1. Issue:
 `java-locator`

You should get the path of the JDK that is located.

Moreover, if you issue `java-locator --jvmlib`, you should get the location of the libjvm dynamic library that is used by JNI.

If you find something that is not sensible, please make sure that your `JAVA_HOME` is exported correctly and pointing to the JDK that you want to use.

**Comment by schmidmt** [comment]
I did try `java-locator --jvmlib` and it returned values that I would expect given the `JAVA_HOME` variable. 

I've tried with a number of jvms but they all have the same issue. 
Debugging here https://github.com/astonbitecode/j4rs/blob/87fe17f04c09324e39e31db0908b4f29da85ffa5/rust/src/api_tweaks/generic.rs#L39
reports the correct libjvm.

Is there an example for running a java method in rust I can try?

**Comment by astonbitecode** [comment]
I guess you could run the tests of j4rs. Just build Java before Rust:

While in rust directory, execute:

`mvn -f ../java/pom.xml clean install && cargo test`

**Comment by astonbitecode** [comment]
Any updates on this? Could the tests be executed?

**Comment by schmidmt** [comment]
The tests all pass. I'll look into this more in the future. For now, it seems it's something in my environment.
