### ISSUE TITLE
Fails while trying to get a value from vector

### ISSUE THREAD

**Issue by naveenann** [astonbitecode/j4rs#28]
Hi,

I am trying to get a value from a vector object but it says the method not found. The method returns a vector object that needs to be iterated. Is there a way we can do it?

`      let ia = vec![InvocationArg::try_from(0).unwrap()];
    let sub_folders = jvm.chain(&root_folder).unwrap()
        .invoke("getSubFolders", &[]).unwrap()
        .invoke("get", &[]).unwrap()
        .collect();`

`Exception in thread "main" org.astonbitecode.j4rs.errors.InvocationException: While invoking method get of Class java.util.Vector
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:73)
Caused by: java.lang.NoSuchMethodException: Method get was not found in java.util.Vector or its ancestors.
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.findMethodInHierarchy(JsonInvocationImpl.java:237)
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.findMethodInHierarchy(JsonInvocationImpl.java:239)
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.findMethodInHierarchy(JsonInvocationImpl.java:239)
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.findMethodInHierarchy(JsonInvocationImpl.java:239)
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeMethod(JsonInvocationImpl.java:169)
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invoke(JsonInvocationImpl.java:70)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JavaError("An Exception was thrown by Java... Please check the logs or the console.")', src\main.rs:29:29
stack backtrace:`

Is there a way we can iterate over an instance ?

**Comment by astonbitecode** [comment]
Hi,

The `java.util.Vector` class indeed does not have a method `get` that takes no arguments. I guess you have forgotten to include your `ia` to the final invoke call?

```rust
let ia = vec![InvocationArg::try_from(0).unwrap()]; 

let sub_folders = jvm.chain(&root_folder).unwrap() 
       .invoke("getSubFolders", &[]).unwrap() 
       .invoke("get", &[ia]).unwrap() .collect();
```

**Comment by naveenann** [comment]
ah yes sorry.

**Comment by naveenann** [comment]
It works only if we use it as a primitive type
`let ia = InvocationArg::try_from(i).unwrap().into_primitive().unwrap();` But this is causing me an issue when i have an recursive function.

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JavaError("Could not find the JNIEnv in the thread local")'`

**Comment by astonbitecode** [comment]
The error that you get, is because probably you haven't initialized a `Jvm` in the current thread. 

Remember that in order to execute j4rs invocations you need to have the Jvm "attached" in your current thread (JNI requirements).

This is done simply with a `let jvm: Jvm = JvmBuilder::new().build()?;`. 

If you have more VM options or arguments defined for the first time you initialize your Jvm, you don't have to repeat them here, because the Java VM is initialized once per process.

Regarding iterating, you can either get the `Iterator` of the `Vector` and iterate over it:

```rust
let iterator = jvm.chain(&root_folder)?
    .invoke("getSubFolders", &[])?
    .invoke("iterator", &[])?
    .collect();

loop {
    let has_next_instance = jvm.invoke(&iterator, "hasNext", &[])?;
    let has_more_elements: bool = jvm.to_rust(has_next_instance)?;
    if !has_more_elements {
        break;
    }
    let next_instance = jvm.invoke(&iterator, "next", &[])?;
    let s: String = jvm.to_rust(next_instance)?;
    println!("{}", s);
}
```

Or, you can get them one by one by knowing the size of the Vector:

```rust
let vector = jvm.invoke(&root_folder, "getSubFolders", &[])?;
let size: i32 = jvm.chain(&vector)?
    .invoke("size", &[])?
    .to_rust().unwrap();

for i in 0..size {
    let s: String = jvm.chain(&vector)?
        .invoke("get", &[InvocationArg::try_from(i)?.into_primitive()?])?
        .to_rust()?;
    println!("{}", s);
}
```


Currently, there is no idiomatic way in j4rs to further simplify iteration, but I am considering implementing one in the future.

**Comment by naveenann** [comment]
Thank you so much for your help. It would be good if we can have few more basic examples.
