### ISSUE TITLE
copy_j4rs_libs_under - support for x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by bhass1** [astonbitecode/j4rs#29]
Currently the rust build utility helper function, `copy_j4rs_libs_under`, doesn't pick up my `x86_64-unknown-linux-musl` build of the `libj4rs*.so`.

Minimal Dockerfile Reproducer:
```
# Dockerfile
FROM rust:1.53.0-alpine
RUN apk update && apk add musl-dev
RUN rustup target add x86_64-unknown-linux-musl
RUN cargo new copy-j4rs-reproducer
WORKDIR copy-j4rs-reproducer
RUN echo -e 'fn main() {\n\
    j4rs::Jvm::copy_j4rs_libs_under("target/j4rs-libs").unwrap();\n\
}\n'\
>> build.rs

RUN echo -e '\
j4rs = "0.13.0"\n\
[build-dependencies]\n\
j4rs = "0.13.0"'\
>> Cargo.toml

RUN RUSTFLAGS='-C target-feature=-crt-static' cargo build --target x86_64-unknown-linux-musl

RUN echo $(ls ./target/j4rs-libs/deps)
RUN echo $(find ./ -name libj4rs* | grep .so)
```

Reproduce with `docker build --no-cache --progress=plain .`

Expected `./target/x86_64-unknown-linux-musl/debug/deps/libj4rs-3eee67990eeab463.so` to be located in `./target/j4rs-libs/deps/.`

**Comment by astonbitecode** [comment]
Thanks for the report. 

There was a host/target triplet issue. I pushed a fix for it and now, if I change a bit the Dockerfile reproducer to use the j4rs from Github:

```
RUN echo -e '\
j4rs = {git="https://github.com/astonbitecode/j4rs"}\n\
[build-dependencies]\n\
j4rs = {git="https://github.com/astonbitecode/j4rs"}'\
>> Cargo.toml
```

I get 

>>  ---> Running in 40257d6049f5
./target/j4rs-libs/deps/libj4rs-9bc75048ee4f0ee6.so ./target/x86_64-unknown-linux-musl/debug/deps/libj4rs-9bc75048ee4f0ee6.so

Please tell me if this is ok for you too.

**Comment by bhass1** [comment]
Works on my end. Thanks for the quick fix!
