### ISSUE TITLE
`Jvm::attach_thread` fails on Android

### ISSUE THREAD

**Issue by s1341** [astonbitecode/j4rs#31]
`Jvm::attach_thread` fails on Android.

Looking at the code (https://github.com/astonbitecode/j4rs/blob/1e177113024332ebaae9aca837c01888fa009bfd/rust/src/api_tweaks/android.rs#L43), it seems like it doesn't actually call `JNI_GetCreatedJavaVMs`. Am I missing something?

**Comment by astonbitecode** [comment]
I think the issue is that you should have a `JNI_OnLoad` in place, in order to set the created VM there. Something like:

```rust
#[allow(non_snake_case)]
#[no_mangle]
pub extern fn JNI_OnLoad(env: *mut JavaVM, _reserved: jobject) -> jint {
    j4rs::set_java_vm(env);
    JNI_VERSION_1_6
}

```
`set_java_vm` [for Android](https://github.com/astonbitecode/j4rs/blob/1e177113024332ebaae9aca837c01888fa009bfd/rust/src/api_tweaks/android.rs#L55) will cache the provided `JavaVM`. 

After that, the `Jvm::attach_thread` should not have issues...

Attaching the thread is actually done in [get_created_vm](https://github.com/astonbitecode/j4rs/blob/1e177113024332ebaae9aca837c01888fa009bfd/rust/src/api.rs#L979).

**Comment by s1341** [comment]
I think it would still be convenient to use `JNI_GetCreatedJavaVMs` if no VM is set, as that way you can get access to the jvm even if your entry point is not a `JNI_OnLoad`. What do you think?

**Comment by astonbitecode** [comment]
You don't __have__ to have `JNI_Onload` as an entrypoint. As mentioned in JNI tips, JNI_OnLoad is called from the correct class loader context, so this is the best place to cache the `JavaVM`, or do any initialization like classes caching etc to avoid classloading issues. 

Anyway, I believe you may call the `set_java_vm` from any point you prefer, but maybe you will fall into other issues... 

Generally the `JNI_GetCreatedJavaVMs` is considered _low level_ for j4rs. Do you want to share your use case? What are you trying to achieve?

**Comment by s1341** [comment]
I'm trying to attach to the existing JVM from `LD_PRELOAD`-ed or injected code.

**Comment by astonbitecode** [comment]
So, there is no possibility to use `JNI_OnLoad`? If not, we may have to sketch out one solution, because j4rs needs the `JavaVM` cached. 

I have to admit that the `JNI_OnLoad` need  for j4rs is not documented and it is something that definitely needs to be done

**Comment by s1341** [comment]
Yeah. It's not trivial to require a `JNI_OnLoad`... I think that the attach functions should try to load the cached `JavaVM`, and if none is available, grab one via `JNI_GetCreatedJavaVMs`...

**Comment by astonbitecode** [comment]
Fair enough. I will get this implemented; if the JavaVM is not located in the cache, it will be retrieved using the `JNI_GetCreatedJavaVMs`.

**Comment by s1341** [comment]
Awesome!
