### ISSUE TITLE
Warning: panic message is not a string literal

### ISSUE THREAD

**Issue by vadimpanchenko991** [astonbitecode/j4rs#34]
Warning: panic message is not a string literal
  --> src/lib.rs:18:1
   |
18 | #[call_from_java("com.company.Class.method")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(non_fmt_panics)]` on by default
   = note: this usage of panic!() is deprecated; it will be a hard error in Rust 2021
   = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/panic-macro-consistency.html>
   = note: this warning originates in the attribute macro `call_from_java` (in Nightly builds, run with -Z macro-backtrace for more info)

This warning comes from line 42 of j4rs_derive-0.1.0/src/lib.rs file:
` _ => panic!("No valid args found in call_from_java. Usage: #[call_from_java(\"full.class.name\")]")`

**Comment by vadimpanchenko991** [comment]
Thank you!

**Comment by astonbitecode** [comment]
Thanks for reporting
