### ISSUE TITLE
org.astonbitecode.j4rs.errors.InstantiationException: Cannot create instance of 

### ISSUE THREAD

**Issue by rollbor** [astonbitecode/j4rs#51]
**Hello, I reported an error while running j4rs，
I need the help of a technical guru, thank you very much, here is the error message and my environment version information**

###  Operation details:
The pre-initialization when my private jar file is called。
Part of my source code:
```
    let jvm: Jvm = JvmBuilder::new().with_default_classloader()
        .classpath_entry(
            ClasspathEntry::new("D:\\work\\utils\\demo\\libs\\java-api-1.0-SNAPSHOT.jar"))
        .build()
        .unwrap();

   //Construct RequestParam  object
    let my_bean = RequestParam {
        data1: "data1_ hello".to_string(),
        data2: "data2_ hello".to_string(),
    };
    
    //create java object
    let ia = InvocationArg::new(&my_bean,
                                "com.rollbor.data.RequestParam");

    //create java instance
    let test_instance = jvm.create_instance("com.rollbor.service.impl.emergencySignalServiceImpl",
                                            &[]).unwrap();

    //Reflection call method
    let string_instance = jvm.invoke(&test_instance,
                                     "get", &[ia]).unwrap();

```

### **Error details:**

```
org.astonbitecode.j4rs.errors.InstantiationException: Cannot create instance of com.rollbor.service.impl.emergencySignalServiceImpl
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.instantiate(NativeInstantiationImpl.java:47)
Caused by: java.lang.ClassNotFoundException: com.rollbor.service.impl.emergencySignalServiceImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.astonbitecode.j4rs.utils.Utils.forNameEnhanced(Utils.java:43)
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.createInstance(NativeInstantiationImpl.java:92)
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.instantiate(NativeInstantiationImpl.java:44)
```
### **Supplement**:
emergencySignalServiceImpl Class has inherited NativeCallbackSupport

### **Environment:**

**j4rs** ：
```
branch：master
tags：v0.15.3
```
**cargo Version**: 
`cargo 1.65.0 (4bc8f24d3 2022-10-20),`

**java Version**:  

```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Operating system**: 
 `windows 10`

**Look forward to your help**

**Comment by astonbitecode** [comment]
Hi,

can you please run your application having set the env var `J4RS_CONSOLE_LOG_LEVEL=debug`:

```
set J4RS_CONSOLE_LOG_LEVEL=debug
cargo run
```
and provide the output?

**Comment by astonbitecode** [comment]
Just noticed that the class name starts with a non-capital letter. This is not common... Is this maybe a spelling mistake?

`com.rollbor.service.impl.emergencySignalServiceImpl`

If yes, apparently this is the issue...

**Comment by rollbor** [comment]
> Just noticed that the class name starts with a non-capital letter. This is not common... Is this maybe a spelling mistake?
> 
> `com.rollbor.service.impl.emergencySignalServiceImpl`
> 
> If yes, apparently this is the issue...

Sorry, this is one of my naming formatting problems, and it actually starts in lower case

**Comment by rollbor** [comment]
> Hi,
> 
> can you please run your application having set the env var `J4RS_CONSOLE_LOG_LEVEL=debug`:
> 
> ```
> set J4RS_CONSOLE_LOG_LEVEL=debug
> cargo run
> ```
> 
> and provide the output?


**This is my debug log：**

```
INFO: Setting classpath to -Djava.class.path=D:\work\utils\demo\target\debug\jassets\j4rs-0.15.3-jar-with-dependencies.jar;D:\work\utils\demo\libs\java-api-1.0-SNAPSHOT.jar
INFO: Setting library path to -Djava.library.path=D:\work\utils\demo\target\debug\deps
INFO: Passing to the Java world the name of the library to load: j4rs-dace6b0392f64691
DEBUG: Creating a Jvm
INFO: No JVMs exist. Creating a new one...
DEBUG: Called set_jni_get_method_id
DEBUG: Called set_jni_get_static_method_id
DEBUG: Called set_jni_new_object
DEBUG: Called set_jni_new_string_utf
DEBUG: Called set_jni_get_string_utf_chars
DEBUG: Called set_jni_release_string_utf_chars
DEBUG: Called set_jni_call_object_method
DEBUG: Called set_jni_call_byte_method
DEBUG: Called set_jni_call_short_method
DEBUG: Called set_jni_call_int_method
DEBUG: Called set_jni_call_long_method
DEBUG: Called set_jni_call_float_method
DEBUG: Called set_jni_call_double_method
DEBUG: Called set_jni_call_void_method
DEBUG: Called set_jni_call_static_object_method
DEBUG: Called set_jni_new_object_array
DEBUG: Called set_jni_set_object_array_element
DEBUG: Called set_jni_exception_check
DEBUG: Called set_jni_exception_describe
DEBUG: Called set_jni_exception_clear
DEBUG: Called set_jni_delete_local_ref
DEBUG: Called set_jni_delete_global_ref
DEBUG: Called set_jni_new_global_ref
DEBUG: Called set_jni_throw_new
DEBUG: Called set_is_same_object
DEBUG: Called set_thread_local_env
DEBUG: Initializing NativeCallbackSupport with libname j4rs-dace6b0392f64691
DEBUG: Invoking static method initialize of class org.astonbitecode.j4rs.api.invocation.NativeCallbackToRustChannelSupport using 1 arguments
DEBUG: Called set_factory_class
DEBUG: Called set_factory_create_for_static_method
DEBUG: Called set_invocation_arg_class
DEBUG: Creating jobject from Rust basic for class java.lang.String
DEBUG: Calling the InvocationArg constructor with 'java.lang.String'
DEBUG: Called set_inv_arg_basic_rust_constructor_method
DEBUG: Called set_java_instance_class
DEBUG: Called set_invoke_static_method
DEBUG: Dropping an instance of known_in_java_world
DEBUG: Dropping an instance of java.lang.String
DEBUG: NativeCallbackSupport initialized
DEBUG: Instantiating class com.rollbor.service.impl.emergencySignalServiceImpl using 0 arguments
DEBUG: Called set_factory_instantiate_method
Exception in thread "main" org.astonbitecode.j4rs.errors.InstantiationException: Cannot create instance of com.rollbor.service.impl.emergencySignalServiceImpl
        at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.instantiate(NativeInstantiationImpl.java:47)Caused by: java.lang.ClassNotFoundException: com.rollbor.service.impl.emergencySignalServiceImpl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.astonbitecode.j4rs.utils.Utils.forNameEnhanced(Utils.java:43)
        at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.createInstance(NativeInstantiationImpl.java:92)
        at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.instantiate(NativeInstantiationImpl.java:44)thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JavaError("An Exception was thrown by Java... Please check the logs or the console.")', src\main.rs:45:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
DEBUG: Called set_thread_local_env
error: process didn't exit successfully: `target\debug\demo.exe` (exit code: 101)
```

**Comment by astonbitecode** [comment]
The logs do not show something special. Your case should work without issues. Please check that:

* The classpath is correct.

More specifically, that the path `D:\work\utils\demo\libs\java-api-1.0-SNAPSHOT.jar` is correct and that the jar contains the class `com.rollbor.service.impl.emergencySignalServiceImpl` in the correct path internally.

* There is a valid constructor in `com.rollbor.service.impl.emergencySignalServiceImpl` that does not accept arguments, since you try to instantiate with `jvm.create_instance("com.rollbor.service.impl.emergencySignalServiceImpl", &[])`

**Comment by rollbor** [comment]
> The logs do not show something special. Your case should work without issues. Please check that:
> 
> * The classpath is correct.
> 
> More specifically, that the path `D:\work\utils\demo\libs\java-api-1.0-SNAPSHOT.jar` is correct and that the jar contains the class `com.rollbor.service.impl.emergencySignalServiceImpl` in the correct path internally.
> 
> * There is a valid constructor in `com.rollbor.service.impl.emergencySignalServiceImpl` that does not accept arguments, since you try to instantiate with `jvm.create_instance("com.rollbor.service.impl.emergencySignalServiceImpl", &[])`

I have checked once according to your prompt, but it is still invalid when I run it again. I am considering whether it is possible that the UNC path in windows system cannot be accessed.

**Comment by astonbitecode** [comment]
It doesn't seem UNC is an issue here because the paths seem normal (D:\work\utils\demo\libs\java-api-1.0-SNAPSHOT.jar)

Do you maybe have some code to share?

**Comment by rollbor** [comment]
java source code：

**Comment by rollbor** [comment]
rust source code：

[rust-demo.zip](https://github.com/astonbitecode/j4rs/files/10869712/rust-demo.zip)

**Comment by astonbitecode** [comment]
It doesn't seem to be a `j4rs` issue.

Your `java-api-1.0-SNAPSHOT.jar` does not actually contain the `com.rollbor.service.impl.emergencySignalServiceImpl` class. 

You may open the jar and see yourself.

Apparently the maven build does not produce the expected...

**Comment by rollbor** [comment]
The path of the jar package opened by decompressing the software is as follows. The jar package can run normally through `java-jar java-api-1.0-SNAPSHOT.jar`

![捕获](https://user-images.githubusercontent.com/27479558/222468517-8fd5080c-6be6-43e8-8ae0-727b830fba11.PNG)

**Comment by astonbitecode** [comment]
The generated jar is a Spring-Boot application. This is spring specific structure and cannot be used as a normal Jar.

If you need to have both Spring Boot jar and a traditional one, you should try something like:

https://codingnconcepts.com/spring-boot/spring-boot-project-as-dependency/

**Comment by rollbor** [comment]
I seem to have found a problem. j4rs searches for class files in MATE-INF class paths, right?

> The generated jar is a Spring-Boot application. This is spring specific structure and cannot be used as a normal Jar.
> 
> If you need to have both Spring Boot jar and a traditional one, you should try something like:
> 
> https://codingnconcepts.com/spring-boot/spring-boot-project-as-dependency/

I seem to have found a problem. j4rs searches for class files in MATE-INF class paths, right?

**Comment by rollbor** [comment]
> The generated jar is a Spring-Boot application. This is spring specific structure and cannot be used as a normal Jar.
> 
> If you need to have both Spring Boot jar and a traditional one, you should try something like:
> 
> https://codingnconcepts.com/spring-boot/spring-boot-project-as-dependency/



Thank you very much for your help. I'll try again. Wish you a happy life!
