### ISSUE TITLE
Heads up for planned jni-sys updates

### ISSUE THREAD

**Issue by rib** [astonbitecode/j4rs#65]
Heya, I just wanted to make sure to give a heads up here that I've been chipping away at some maintenance chores for jni-sys and based on issues I've seen while working on the `jni` crate I was planning a few semver breaking changes.

It'd be good if you can take a look at the 'Release 0.4' milestone here: https://github.com/jni-rs/jni-sys/milestone/1

The two notable changes are:
1. making `jboolean` an alias for `bool`: ref https://github.com/jni-rs/jni-sys/issues/19, https://github.com/jni-rs/jni-rs/pull/400#issuecomment-1399511026 and https://github.com/jni-rs/jni-sys/pull/23
2. Turning `JNINativeInterface` + `JNIInvokeInterface_` into unions that namespace function pointers by the JNI version they were added (and remove the misleading `Option` wrappers), ref: https://github.com/jni-rs/jni-sys/pull/28 and https://github.com/jni-rs/jni-sys/pull/25

The latter change in particular may invole some boilerplate changes here but at least as far as the `jni` crate goes I'm glad I looked at this this since it has highlighted several places where the `jni` crate was using > 1.1 functions without checking the version at runtime.

**Comment by astonbitecode** [comment]
Thanks for the heads-up, much appreciated.

This was parked for some time, but I guess the time has come to deal with it.
