### ISSUE TITLE
Excessive log issue

### ISSUE THREAD

**Issue by XizhiXu** [astonbitecode/j4rs#66]
Hello @astonbitecode I'd like to ask for a log change here:
https://github.com/astonbitecode/j4rs/blob/7c71b061f7abd2de0eff5209f76f27a6b35135d8/rust/src/api/mod.rs#L143

Currently, we use **Jvm** in an event looper in Rust. We are seeing lots of logs from this and valuable information is missed from the console.

<img width="1657" alt="image" src="https://github.com/astonbitecode/j4rs/assets/1848565/342512e9-64b4-434f-9a7b-de7b9009d668">

is it possible to move this to the **else** branch? We usually know the **Jvm** is there and creating it should be the rare case we should pay attention to.

**Comment by astonbitecode** [comment]
This should indeed be in debug level.

**Comment by XizhiXu** [comment]
Hey @astonbitecode what is your release plan for the next version of the rust crate? It would be much appreciated if we can deploy this update soon to reduce our devs' debug overhead.
