### ISSUE TITLE
when run j4rs in build.rs, if the target is wasm-unknown-unknown, jvm cannot created.

### ISSUE THREAD

**Issue by lencil** [astonbitecode/j4rs#67]
I have some task to run in build.rs. It need to call a jar file method before the project run. If run the target with host machine target, it work fine. If compile to wasm, the build script will fail.

  --- stderr
  thread 'main' panicked at 'Failed to initialize JVM: GeneralError("Error { kind: NotFound, message: \"The system cannot find the file specified. (os error 2)\" }")', xxx\build.rs:246:69
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
     1: core::panicking::panic_fmt
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
     2: core::result::unwrap_failed
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\result.rs:1687
     3: enum2$<core::result::Result<j4rs::api::Jvm,enum2$<j4rs::errors::J4RsError> > >::expect<j4rs::api::Jvm,enum2$<j4rs::errors::J4RsError> >

**Comment by astonbitecode** [comment]
Thanks for the report.

I have never tried to build `j4rs` for wasm, but my feeling is that it is not compatible. 

Even if you overpass the [libloading issues](https://github.com/astonbitecode/j4rs/issues/53) using the [no-runtime-libloading](https://github.com/astonbitecode/j4rs/issues/55#issuecomment-1520076571) feature (I need to proceed with some documentation, honestly), I am not sure how the sandbox will allow correct execution... Maybe this is the reason of the `The system cannot find the file specified` error.

**Comment by lencil** [comment]
> 

not compile j4rs in wasm product. just use it in build.rs in host to do some prepared build task to generate some resource, before begin wasm building.

**Comment by astonbitecode** [comment]
As you also noticed in your initial comment:

> If run the target with host machine target, it work fine. If compile to wasm, the build script will fail.

I believe the target is the same during the `build.rs` execution. You may try debugging seeing the [`target_os`](https://doc.rust-lang.org/reference/conditional-compilation.html#target_os) in your build file.

**Comment by lencil** [comment]
> As you also noticed in your initial comment:
> 
> > If run the target with host machine target, it work fine. If compile to wasm, the build script will fail.
> 
> I believe the target is the same during the `build.rs` execution. You may try debugging seeing the [`target_arch`](https://doc.rust-lang.org/reference/conditional-compilation.html#target_arch) or [`target_os`](https://doc.rust-lang.org/reference/conditional-compilation.html#target_os) in your build file.

I found some solutions hack:
1. I found j4rs use java-locator to search java install, which check the CARGO_CFG_TARGET_OS environment var. so just change the value to the HOST Target os by env::set_var("CARGO_CFG_TARGET_OS", "your host os");
2. When the build.rs target is not the product target, the j4rs jvm base_dir may not be right. so set the correct base_dir when creating jvm with with_base_path()

I hope my work could help others:)

**Comment by astonbitecode** [comment]
Good to know you found a way to go... However, I would say that messing with cargo env vars is not so good idea. Maybe other crates being built need the actual target you are building against...
