### ISSUE TITLE
Rust calling Java does not support overloaded methods.

### ISSUE THREAD

**Issue by MarkMjw** [astonbitecode/j4rs#69]
The Java class includes two overloaded methods, the reflection call will crash, and the function parameter types are different (ps: the different number of parameters is also the same problem), as follows:

```Kotlin
    @JvmStatic
    fun function(k1: String?, k2: String?): String? {
        return "$k1 or $k2"
    }

    @JvmStatic
    fun function(k1: String?, k2: Int?): String? {
        return "$k1 and $2"
    }
```

```rust
   let result = jvm.invoke_static(
        "com.android.rust.RustApi",
        "function",
        &[InvocationArg::try_from("key").unwrap(), InvocationArg::try_from(123456).unwrap()],
    ).map_err(|error| format!("{}", error));
```

**Comment by astonbitecode** [comment]
I cannot see how the overloading support is broken.

For example, this works as expected:

#### Java

```java
public static String function(String k1, String k2) {
    return String.format("%s or %s", k1, k2);
}

public static String function(String k1, Integer k2) {
    return String.format("%s and %s", k1, k2);
}
```

#### Rust

```rust
let result_instance_1 = jvm.invoke_static(
   "my.Test",
   "function",
    &[InvocationArg::try_from("key").unwrap(), InvocationArg::try_from(123456).unwrap()],
)?;
let result_1: String = jvm.to_rust(result_instance_1)?;
println!("result_1: {}", result_1);

let result_instance_2 = jvm.invoke_static(
    "my.Test",
    "function",
    &[InvocationArg::try_from("key").unwrap(), InvocationArg::try_from("key2").unwrap()],
)?;
let result_2: String = jvm.to_rust(result_instance_2)?;
println!("result_2: {}", result_2);
```

The output is:

> result_1: key and 123456
result_2: key or key2

I do not know how kotlin works, but, could it be that `Int?` is actually a primitive and not an object? 

In that case you should try what is described in the README [section for primitives](https://github.com/astonbitecode/j4rs#java-primitives).

Generally, it would be good to have some logs from the failure of `j4rs`, if possible with [debug level](https://github.com/astonbitecode/j4rs#how-can-i-enable-debug-logging).

**Comment by MarkMjw** [comment]
Thanks for your response. Following your guidance, I resolve the problem. 
```rust
let ia = InvocationArg::try_from(1_i32)?.into_primitive()?;
```
 is now working as expected.
