### ISSUE TITLE
arm64 Java support

### ISSUE THREAD

**Issue by Heliozoa** [astonbitecode/j4rs#70]
Hi,
Thanks for your work on j4rs.

I'm not sure if this is due to j4rs or something else, but we are having some issue trying to use j4rs with arm64 versions of Java. (Original issue here: https://github.com/rage/tmc-vscode/issues/677)

Unfortunately we don't have Macs to replicate the issue with locally, but after changing the `setup-java` action in a GitHub workflow to use the `aarch64` architecture on the `macos-latest` target, I get a similar error:

`Could not load the jvm dynamic library: DlOpen { desc: \"dlopen(/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-7/aarch64/Contents/Home/lib/server/libjvm.dylib, 0x0005): tried: \\'/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-7/aarch64/Contents/Home/lib/server/libjvm.dylib\\' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))\" }`

Is this something that's unsupported by j4rs, or are we missing some configuration to make it work? If it's of interest, the full workflow logs are here https://github.com/rage/tmc-langs-rust/actions/runs/5934564656/job/16091662626?pr=207 and most of the relevant code in our project is around here https://github.com/rage/tmc-langs-rust/blob/9cc73a19149789ca461573b016f59b4c72c5446a/crates/plugins/java/src/lib.rs#L142

**Comment by astonbitecode** [comment]
Hi,

I also do not own a mac, but there is a [workflow](https://github.com/astonbitecode/j4rs/actions/runs/5724686327/job/15511680478), where `j4rs` is tested for macos.

The error you get says that the `jvm` is located in the host, but the architecture is not correct... It seems that `j4rs` tries to build in `x86_64`, but the host has `arm64`. 

Do you have any special configuration for cross-compiling? If yes, could you make sure the targets are set up correctly to `arm64`?

**Comment by Heliozoa** [comment]
The `setup-java` action will default to x64 Java if no architecture is defined, even on `macos-latest`. I was surprised to learn this myself, but it can be seen in the workflow logs:
`Downloading Java 17.0.8+7 (Adopt-Hotspot) from https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.8%2B7/OpenJDK17U-jdk_x64_mac_hotspot_17.0.8_7.tar.gz ...`.

I had a similar workflow, and after the issue was reported I tried changing it to use `aarch64` on `macos-latest`, and was able to replicate the issue in CI:

https://github.com/rage/tmc-langs-rust/blob/jdk-17/.github/workflows/test.yml#L65

https://github.com/rage/tmc-langs-rust/actions/runs/5934564656/job/16091662626

`Downloading Java 17.0.8+7 (Temurin-Hotspot) from https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.8%2B7/OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.8_7.tar.gz ...`

`Could not load the jvm dynamic library: DlOpen { desc: \"dlopen(/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-7/aarch64/Contents/Home/lib/server/libjvm.dylib, 0x0005): tried: \\'/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-7/aarch64/Contents/Home/lib/server/libjvm.dylib\\' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))\" }"`

**Comment by astonbitecode** [comment]
Thanks for this, I was not aware! I will check the `j4rs` workflow and try to add `aarch64` hopefully in the day.

That being said, should you not cross-compile your crate, using something like:

`cargo build --target=aarch64-unknown-linux-gnu` ?

**Comment by Heliozoa** [comment]
Oh, I think you are right. I assumed that the default target on macos-latest would be aarch64, but it seems that is not the case... I will look into it more and let you know if it fixes the issue, thank you.

**Comment by astonbitecode** [comment]
Hi @Heliozoa, I am doing some housekeeping and saw that the initial issue is fixed in the `tmc-vscode` repo. 

Does it mean we can close this one too?

**Comment by Heliozoa** [comment]
Yes, I forgot to close this after the student confirmed their issue was fixed. Thanks for your help in locating the problem!
