### ISSUE TITLE
how to achieve this ?

### ISSUE THREAD

**Issue by andrewpedia** [astonbitecode/j4rs#74]
there is a java method named "xxx" which calls a native function from native lib,
how to invoke xxx from rust side?

**Comment by astonbitecode** [comment]
You do not need anything special to achieve this.

Java calls rust via `j4rs` and then it is up to the Rust code to do anything, including calling other Rust functions.

**Comment by andrewpedia** [comment]
I need to call java from rust , and that java function calls a native jni .
can this be done with j4rs?

BTW,how to add native libs to this jvm


thanks a lot .

**Comment by astonbitecode** [comment]
Yes this can be done. Please read the documentation in the [README](https://github.com/astonbitecode/j4rs).

Calling Java from Rust is explained [here](https://github.com/astonbitecode/j4rs#Basics).
Calling Rust from Java is explained [here](https://github.com/astonbitecode/j4rs#Java-to-Rust-support)
