### ISSUE TITLE
Borrow checker problem

### ISSUE THREAD

**Issue by TropicalDog17** [astonbitecode/j4rs#76]
Hi, I want to call Java library about NLP from Rust side.
The original Java code is this
```  String[] annotators = {"wseg", "pos", "ner", "parse"}; 
        VnCoreNLP pipeline = new VnCoreNLP(annotators); 
    
        String str = "Some Text"; 
        
        Annotation annotation = new Annotation(str); 
        pipeline.annotate(annotation); 
        System.out.println(annotation.toString());
```
And I want to use Rust to call from this Java library. I have tried this
```
...
    let i = InvocationArg::try_from(annotators.as_slice())?;
    let pipeline = jvm.create_instance("vn.pipeline.VnCoreNLP", &[i])?;
    let s = InvocationArg::try_from(String::from("Some Text"))?;
    let annotation = jvm.create_instance("vn.pipeline.Annotation", &[s])?;
    let i_annotation = InvocationArg::try_from(annotation)?; // Value moved here
    let _ = jvm.invoke(&pipeline, "annotate", &[i_annotation]);
    let string_instance = jvm.invoke(&annotation, "toString", &Vec::new()); // Value used after move
```
But Rust doesn't allow me to do this, since annotation is moved in the `try_from` line. Any suggestion/workaround for this? Am I missing something important? Thank you.

**Comment by TropicalDog17** [comment]
@astonbitecode I had no idea about the clone_instance method. Thanks a lot for your speedy help!
Btw I wonder how the `clone_instance` work, 
``` rust
let annotation = jvm.create_instance("vn.pipeline.Annotation", &[s])?;
let annotation2 = jvm.clone_instance(&annotation)?;
```
Does these two instances connected to each other, since according to the Java code it modifies the annotation in-place. But `annotation2` is modified as well when I pass the `annotation` to the pipeline.
``` java
        Annotation annotation = new Annotation(str); 
        pipeline.annotate(annotation);
```

**Comment by astonbitecode** [comment]
Well, I must admit that `clone_instance` is not the perfect name... 

From the Java point of view, a clone is the creation of a new instance, independent from the original one. 
From the Rust point of view, a `clone_instance` is actually the creation of a new `Instance`, which is a _reference_ to the initial `Instance`.

Please let me know if you can propose a better naming...

**Comment by TropicalDog17** [comment]
I guess you should consider including it in the documentation for better clarity. Anyway, thanks a lot for your response.

**Comment by astonbitecode** [comment]
I am planning to create wiki pages containing such pitfalls / things that need more explanation.

Hopefully soon...

Thanks for reporting
