### ISSUE TITLE
UB/Race condition inside invoke()

### ISSUE THREAD

**Issue by lexika979** [astonbitecode/j4rs#82]
Hello,
Somehow, i've managed to trigger a race condition/ub inside j4rs (Or maybe i'm just using it wrong :P).
75% of the times when i run it, it just works, the other 25% i get the error seen in the screenshot.
Unfortunately, im under a strict NDA, so i cannot share much more code and had to heavily censor the screenshot. I tried my best to leave the needed information in there.
The lines in question:
```
    let configuration_layer_builder = jvm.invoke(
        &configuration_layer_builder,
        "withConfigurations",
        &vec![InvocationArg::from(jvm.create_java_array(
            "de.xxxxxx.configuration.Configuration",
            &vec![InvocationArg::from(configuration)],
        )?)],
    )?;
```
The signature of the java function:
`public Builder withConfigurations(@NonNull Configuration... configurations)`

Logs:
![grafik](https://github.com/astonbitecode/j4rs/assets/83946527/3512fa5f-7898-4d2f-86fd-d236604b3c99)

I'd highly appreciate any kind of help.

**Comment by lexika979** [comment]
Also, there's a second function defined that's an overload of the first one, with this signature:
`public Builder withConfigurations(@NonNull List<Configuration> configurations)`
Could it be that these two are clashing?

**Comment by lexika979** [comment]
Here are the debug logs for both cases, i've marked the line where it usually crashes on the second one.
![grafik](https://github.com/astonbitecode/j4rs/assets/83946527/d6b0a0fc-f66a-4dfd-8485-c0cce587bbb4)
![grafik](https://github.com/astonbitecode/j4rs/assets/83946527/8f9b43d2-0428-4bdc-a571-eb612f282f12)

**Comment by astonbitecode** [comment]
Hi,

I tried to reproduce the issue by having two overloaded methods, one with argument `List` and one with `Array` (variadic) but I don't get ant failures.

Do you have access to the Java code, in order to change the signature of the overloaded method with the `List` argument, adding for example one additional `boolean` argument and try again? I just want to find out if the issue is in overloading or not.

**Comment by lexika979** [comment]
Yes, i do have access to the source code.
I just recompiled a version where i added a boolean argument to the overload that takes the list, and tried that -  With the same outcome.

**Comment by lexika979** [comment]
Could this issue be related to the @NonNull annotation thats present on both methods?

**Comment by lexika979** [comment]
I replaced the wrong jar after modifying it, sorry!
Can confirm, it works now.
Is there a temporary workaround for this util the fix is implemented? Unfortunately, i do not have a way to quickly get the new jar rolled out to production util end of next week.

**Comment by astonbitecode** [comment]
Unfortunately, there is no workaround. 

However, I implemented a fix and you may try using the master branch in Github as dependency.

Please, do so in order to see if it works for your case.
