### ISSUE TITLE
Calling main method with invoke_static

### ISSUE THREAD

**Issue by owen-hope** [astonbitecode/j4rs#9]
I am trying to call the main method of a simple java jar program using the invoke_static method in rust but keep receiving an error.

hello.java:
`public class hello {
    public static void main(String[] args) {
        System.out.println("Hello rust");
    }
}`

and am getting this error:
`Exception in thread "main" org.astonbitecode.j4rs.errors.InvocationException: Error while invoking method main of Class hello
        at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeStatic(JsonInvocationImpl.java:74)
Caused by: java.lang.NoSuchMethodException: Method main was not found in hello or its ancestors.`

Defining another method in java and calling it in rust works perfectly fine. Is there a reason for not being able to call the main method?

**Comment by astonbitecode** [comment]
Can you please share the code you use to achieve the call? Even if you don't want to pass arguments to the `public static void main(String[] args)`, the method still needs an empty String array to work correctly. 

You should create an empty String array instance: 
`let empty_arr_instance = jvm.create_java_array("java.lang.String", &[])?;`

Use the instance as argument:
`let empty_arg = InvocationArg::try_from(empty_arr_instance)?;`

And then you pass the `empty_arg` to your invocation call:

`let _ = jvm.invoke_static("my.Main", "main", empty_arg)?;`

**Comment by owen-hope** [comment]
This is currently the code I have written with your suggestions.

`    let empty_array = jvm.create_java_array("java.lang.String", &[]).unwrap();
    let empty_arg = InvocationArg::try_from(empty_array).unwrap();

    let _ = jvm.invoke_static(
        "hello",
        "main",
        &[empty_arg])
        .unwrap();`

when I tried `let _ = jvm.invoke_static("hello", "main", empty_arg).unwrap();`
I received this error:
`error[E0308]: mismatched types
  --> src/main.rs:25:9
   |
25 |         empty_arg)
   |         ^^^^^^^^^ expected reference, found enum  j4rs::api::InvocationArg
   |
   = note: expected type &[j4rs::api::InvocationArg]
              found type j4rs::api::InvocationArg`

**Comment by astonbitecode** [comment]
This is a Rust compilation error rather than the runtime exception from Java world that you had before. 

I just tested the following code which compiles and runs fine:

```rust
let empty_arr_instance = jvm.create_java_array("java.lang.String", &[]).unwrap();
let empty_arg = InvocationArg::try_from(empty_arr_instance).unwrap();

let _ = jvm.invoke_static("hello", "main", &[empty_arg]).unwrap();
```
As the compilation error suggests, make sure that you pass a &[InvocationArg] to the invoka_static 3rd argument.

**Comment by owen-hope** [comment]
It is now running correctly sorry for that. Thanks for your help!
