### ISSUE TITLE
Cannot access nested class

### ISSUE THREAD

**Issue by rukai** [astonbitecode/j4rs#92]
Consider the following reproduction:
```rust
use j4rs::{InvocationArg, Jvm, JvmBuilder, MavenArtifact};

fn main() {
    let jvm: Jvm = JvmBuilder::new().build().unwrap();

    jvm.deploy_artifact(&MavenArtifact::from("org.apache.kafka:kafka-clients:3.7.0"))
        .unwrap();
    jvm.deploy_artifact(&MavenArtifact::from("org.slf4j:slf4j-api:1.7.36"))
        .unwrap();
    jvm.deploy_artifact(&MavenArtifact::from("org.slf4j:slf4j-simple:1.7.36"))
        .unwrap();

    // This works just fine
    let access_mode_enum = jvm.static_class("java.nio.file.AccessMode").unwrap();
    let _access_mode_write = jvm.field(&access_mode_enum, "WRITE").unwrap();

    // this will trigger the issue
    let resource_type = jvm
        .static_class("org.apache.kafka.common.config.ConfigResource.Type")
        .unwrap();
    let _resource_type = jvm.field(&resource_type, "TOPIC").unwrap();

    // this will also trigger the issue
    let _resource_type = jvm
        .invoke_static(
            "org.apache.kafka.common.config.ConfigResource.Type",
            "valueOf",
            &[InvocationArg::try_from("TOPIC").unwrap()],
        )
        .unwrap();
}
```

I am trying to construct the type: https://docs.confluent.io/platform/current/clients/javadocs/javadoc/org/apache/kafka/common/config/ConfigResource.Type.html#enum.constant.detail

As far as I can tell I have correctly specified the type at `org.apache.kafka.common.config.ConfigResource.Type` but I dont seem to be able to access it while I can access `java.nio.file.AccessMode` just fine.
I am guessing that the problem is due to it being a nested class, but that may not actually be the cause.

**Comment by astonbitecode** [comment]
Since `Type` is inner class of `org.apache.kafka.common.config.ConfigResource`, it can be accessed using `$`like:

```rust
let resource_type = jvm
    .static_class("org.apache.kafka.common.config.ConfigResource$Type")
    .unwrap();
let _resource_type = jvm.field(&resource_type, "TOPIC").unwrap();
```

**Comment by rukai** [comment]
Oooh, thanks!
I don't think this $ syntax is something regular users of java are familiar with, would it make sense to add a small section to the readme on accessing nested classes?
