### ISSUE TITLE
How to copy byte[] from Java to Rust

### ISSUE THREAD

**Issue by pickleburger** [astonbitecode/j4rs#96]
Hello,

I have a method in Java which returns a `byte[]`. How can I copy the return value into a Rust byte array, e.g. `Vec<u8>` efficiently (with minimal serialization/deserialization)?

Thanks!

**Comment by pickleburger** [comment]
@astonbitecode thanks for the quick response. I'm wondering if you are open to accept a PR for handling just primitive arrays?

**Comment by astonbitecode** [comment]
Sure, please go on for the PR.

**Comment by pickleburger** [comment]
Thank you! I just created https://github.com/astonbitecode/j4rs/pull/97

Can you please have a look?

**Comment by astonbitecode** [comment]
Implemented in PR #97.

Thanks @pickleburger
