### ISSUE TITLE
Getting exception text in case of error

### ISSUE THREAD

**Issue by lexika979** [astonbitecode/j4rs#98]
Would it be possible to get the actual text + stacktrace of the exception if one is thrown during a call? That would be super helpful for diagnostics in a production environment where access to the console isnt always possible without jumping through hoops.

Regards

**Comment by astonbitecode** [comment]
This is indeed very helpful, thanks for the proposal!

I implemented filling up the Java errors with the actual throwable info.

Please have a look and see if this works for you too.

**Comment by lexika979** [comment]
Will do next week when I'm back in office! Thank you for the quick response and help.

**Comment by astonbitecode** [comment]
I guess you mean to remove the parts of the stacktrace that are generated by the `j4rs` internals, leaving the rest of the stacktrace intact... This seems reasonable.

**Comment by lexika979** [comment]
Works like a charm! Thank you so much!
